-- USUÁRIO
--CREATE ROLE USER_AUTH WITH LOGIN PASSWORD ${AUTH_POSTGRESQL_PASS};

-- SCHEMA
--CREATE SCHEMA AUTH AUTHORIZATION USER_AUTH;

-- PRIVILÉGIOS
--GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA AUTH TO USER_AUTH;

CREATE TABLE AUTH.USERS (
    ID UUID NOT NULL,
    USERNAME VARCHAR(11) NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    ROLE VARCHAR(5) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY(ID),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME)
);
CREATE INDEX IDX_USERS_USERNAME ON AUTH.USERS(USERNAME);